# Generated by Django 3.2.5 on 2021-07-09 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatzbychee', '0002_auto_20210709_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetopic',
            options={'verbose_name_plural': 'messages'},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
